#pragma config(UART_Usage, UART2, uartNotUsed, baudRate4800, IOPins, None, None)
#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           frontLeft,     tmotorVex393_HBridge, openLoop, reversed, encoderPort, I2C_1)
#pragma config(Motor,  port2,           backLeft,      tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           frontRight,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           backRight,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           armMotor1,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           armMotor2,     tmotorNone, openLoop)
#pragma config(Motor,  port7,           armMotor3,     tmotorNone, openLoop)
#pragma config(Motor,  port8,           armMotor4,     tmotorNone, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks
  // running between Autonomous and Driver controlled modes. You will need to
  // manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

  // All activities that occur before the competition starts
  // Example: clearing encoders, setting servo positions, ...
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/
void autoDrive(float speed, float sec)
{
	motor(frontLeft) = speed;
	motor(frontRight) = speed;
	motor(backLeft) = speed;
	motor(backRight) = speed;
	sec *=1000;
	wait1Msec(sec);
}

void autoStop()
{
	motor(frontLeft) = 0;
	motor(frontRight) = 0;
	motor(backLeft) = 0;
	motor(backRight) = 0;
}
void autoArm(int sec)
{
	motor(armMotor1) = 127;
	motor(armMotor2) = 127;
	motor(armMotor3) = 127;
	motor(armMotor4) = 127;
	sec*=1000;
	wait1Msec(sec);
}
task autonomous()
{
		autoDrive(127, 5);
		autoStop();
		autoArm(3);
}
task teleArm()
{
	if(vexRT(Btn5U)){
	for(int speed = 0; speed <= 127; speed+=5)
	{
	motor(armMotor1) = speed;
	motor(armMotor2) = speed;
	motor(armMotor3) = speed;
	motor(armMotor4) = speed;
	}
	motor(armMotor1) = 127;
	motor(armMotor2) = 127;
	motor(armMotor3) = 127;
	motor(armMotor4) = 127;
}
	else if(vexRT(Btn5D))
{
	{
	for(int speed = 127; speed >= -127; speed-=5)
	{
	motor(armMotor1) = speed;
	motor(armMotor2) = speed;
	motor(armMotor3) = speed;
	motor(armMotor4) = speed;
	}
	wait1Msec(1000);
	motor(armMotor1) = 0;
	motor(armMotor2) = 0;
	motor(armMotor3) = 0;
	motor(armMotor4) = 0;
}
}
}

task teleDrive()
{
	motor(frontLeft) = vexRT(Ch2);
	motor(backLeft) = vexRT(Ch2);
	motor(backRight) = vexRT(Ch3);
	motor(frontRight) = vexRT(Ch3);
}
task usercontrol()
{
  startTask(teleDrive);
  startTask(teleArm);
  while (true)
  {
  	wait1Msec(1);
  }
}
